# Generated by Django 4.2.7 on 2023-11-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_vlog', '0002_alter_blog_vlog_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_vlog_post',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
