# Generated by Django 4.2.7 on 2023-11-20 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog_vlog', '0003_alter_blog_vlog_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_vlog_post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
